name: mssql
namespace: mssql
appLabel: mssql
serviceName: mssql
replicas: 1
securityContext:
  fsGroup: 10001
container:
  name: mssql
  image: "mcr.microsoft.com/mssql/server:2019-latest"

service:
  name: mssql-0
  namespace: mssql
  selector:
    podName: mssql-0
  ports:
    port: 1433
    targetPort: 1433

certificate:
  name: mssql-certs
  namespace: mssql
  secretName: mssql-certs-secret
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  commonName: "{{ .Release.Name }}-mssql-hostname"  # Replace with dynamic hostname if needed
  dnsNames:
    - "{{ .Release.Name }}-mssql-hostname"  # Replace with dynamic hostname if needed
    - "mssql-0.mssql.svc.cluster.local"
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048

configMap:
  name: mssql
  namespace: mssql
  data:
    mssqlConfLines:
      - "[EULA]"
      - "accepteula = Y"
      - "accepteulaml = Y"
      - ""
      - "[coredump]"
      - "captureminiandfull = true"
      - "coredumptype = full"
      - ""
      - "[hadr]"
      - "hadrenabled = 1"
      - ""
      - "[language]"
      - "lcid = 1033"
      - ""
      - "[network]"
      - "tlscert = /var/opt/mssql/sslcert/tls.crt"
      - "tlskey = /var/opt/mssql/sslcert/tls.key"
      - "tlsprotocols = 1.2"
      - "forceencryption = 0"
