name: mssql
namespace: mssql
appLabel: mssql
serviceName: mssql
replicas: 1
securityContext:
  fsGroup: 10001
container:
  name: mssql
  image: "mcr.microsoft.com/mssql/server:2019-latest"

service:
  name: mssql-0
  namespace: mssql
  selector:
    podName: mssql-0
  ports:
    port: 1433
    targetPort: 1433

certificate:
  name: mssql-certs
  namespace: mssql
  secretName: mssql-certs-secret
  commonName: "my-mssql-hostname.com"  
  dnsNames:
    - "my-mssql-hostname.com"  
    - "mssql-0.mssql.svc.cluster.local"

configMap:
  name: mssql-config
  data:
    EULA: "Y"
    accepteulaml: "Y"
    captureminiandfull: "true"
    coredumptype: "full"
    hadrenabled: "1"
    lcid: "1033"
    tlscert: "/var/opt/mssql/sslcert/tls.crt"
    tlskey: "/var/opt/mssql/sslcert/tls.key"
    tlsprotocols: "1.2"
    forceencryption: "0"



addWindowsLogin: true
dnsUrl: polyseam-dc1.polyseam.com
privilegedadaccount: superuser
dnsIp: 0.0.0.0
