apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.configMap.namespace }}
data:
  mssql.conf: |
    {{- range .Values.configMap.data.mssqlConfLines }}
    {{ . }}
    {{- end }}
